version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
init:
- ps: new-itemproperty -path "HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319" -name "SchUseStrongCrypto" -Value 1 -PropertyType "DWord";
- ps: new-itemproperty -path "HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319" -name "SchUseStrongCrypto" -Value 1 -PropertyType "DWord";
build_script:
- ps: .\build.bat
test: off
artifacts:
- path: Release/test.zip
  name: test.zip
- path: Release/foo_input_vgmstream.fb2k-component
  name: foo_input_vgmstream.fb2k-component
